### ISSUE TITLE
pip install 报找不到模块

### ISSUE THREAD

**Issue by Mufanc** [likianta/pyportable-installer#1]
在终端执行 `pip install pyportable-installer` 产生如下报错：
```
ERROR: Could not find a version that satisfies the requirement pyportable-installer (from versions: none)
ERROR: No matching distribution found for pyportable-installer
```
测试清华源和官方源均有此问题

**Comment by likianta** [comment]
你好, 该问题是由 Python 版本不支持产生的.

请注意 pyportable-installer 仅支持 Python 3.9 及以上版本.

运行 pyportable-installer 也需要 Python 3.9 及以上版本的解释器. 但打包的目标 Python 版本是可调的. 如需启用此特性, 请尝试最新发布的版本 4.0.0b2:

```
pip3.9 install pyportable-installer==4.0.0b2
```

*附件供参考 [gsmr_testbuild_20210913.zip](https://github.com/Likianta/pyportable-installer/files/7153561/gsmr_testbuild_20210913.zip)*

**Comment by Mufanc** [comment]
感谢解答！我会考虑调整项目中使用的 Python 版本，并使用 pyportable-installer 代替 pyinstaller

**Comment by lededev** [comment]
那么现在能支持Python 3.10吗？3.10正式版已经出来一段时间了。pyinstaller还没正式支持3.10。

**Comment by likianta** [comment]
你好. 在九月份 (该 issue 提出时) 仅在 Python 3.9 上进行了充分测试; 前段时间我将版本要求降低到了 Python 3.8 以上.

即理论上 Python 3.8, 3.9, 3.10 均可以运行 pyportable-installer. 但目前仅对 Python 3.9 以及最近对 Python 3.8 进行了充分测试.

如果你需要在 Python 3.10 上立即使用, 请注意以下事项:

- `配置文件:build:venv:python_version` 的值请填写 "3.10"
- `配置文件:build:compiler:options:pyportable_crypto:key` 暂勿使用 "_trial" 作为值 (该问题将接下来几天解决)

![20211024235026](https://user-images.githubusercontent.com/27986259/138601894-58fff5b8-1a91-46b9-b2d8-24abb5ea109d.png)
