### ISSUE TITLE
ImportError: cannot import name 'currdir' from 'lk_utils.filesniff

### ISSUE THREAD

**Issue by cloveses** [likianta/pyportable-installer#10]
from pyportable_installer import full_build
error:ImportError: cannot import name 'currdir' from 'lk_utils.filesniff

**Comment by likianta** [comment]
The dependency version is not correct, I've tried fixed it.

*Before*: `lk-utils>=2.4.1`

*After*: `lk-utils>=2.4.1,<2.5.0`

If you installed this package from PyPI, please upgrade it: `pip install -U pyportable-installer`.

If you cloned the repo, please pull the latest commits and check your lk-utils version (something like below):

```sh
pip uninstall lk-utils
pip install "lk-utils>=2.4.1,<2.5.0"
```
