### ISSUE TITLE
配置无控制台打包，移动后仍有控制台

### ISSUE THREAD

**Issue by XingZiiii** [likianta/pyportable-installer#11]
我使用无控制台模式（"enable_console": false）打包后，将软件传到其他电脑，运行时仍会有控制台弹出。请问这是bug还是配置到其他电脑运行要重新打包？

**Comment by likianta** [comment]
`enable_console` 选项是由 [gen-exe](https://github.com/silvandeleemput/gen-exe) 库控制. 

一个已知的问题是, 当该选项设置为 `false` 时, 生成的 exe 文件会在双击启动时产生一个 "一闪即逝" 的控制台弹窗. 不知道是否符合你的问题.

如果控制台是持续存在, 对于此情况我暂时未能遇到, 无法为你解决.

---

如果你希望定位是否为 [gen-exe](https://github.com/silvandeleemput/gen-exe) 导致的该问题, 下面是一个最小的可复现脚本:

```py
# test_exe_with_no_console.py

import sys
from pathlib import Path
from genexe.generate_exe import generate_exe  # pip install gen-exe

bat_cmd = '{python} -m webbrowser -t github.com'.format(
    python=sys.executable
)

generate_exe(
    target=Path('test.exe'),
    command=bat_cmd,
    icon_file=None,
    show_console=False,
)
```

首先安装 `pip install gen-exe`, 使用 python 运行此脚本, 会生成一个 "test.exe" 文件, 双击此文件会打开浏览器并访问 github 主页.

请测试它是否仍然会有控制台弹出.
