### ISSUE TITLE
找不到指定的模块: . inject

### ISSUE THREAD

**Issue by MeteorShower2004** [likianta/pyportable-installer#2]
你好，我在尝试打包此项目的示例文件 _hello_world_ ，启动后提示找不到模块。
### 详细信息：
_Runtime Exception: Traceback (most recent call last):
  File "...\hello_world_0.4.7\src\pylauncher.py", line 150, in <module>
    mod = import_module(conf['TARGET_MOD'], conf['TARGET_PKG'])
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "...\hello_world_0.4.7\src\hello_world\hello.py", line 1, in <module>
    from pyportable_runtime import inject
  File "...\hello_world_0.4.7\lib\pyportable_runtime\__init__.py", line 1, in <module>
    from .inject import inject
ImportError: DLL load failed while importing inject: 找不到指定的模块。_
### 构建时输出的日志
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\path_model.py:12    >>      <module>        >>
        [D2952] ASSETS_ENTRY = PACKAGE
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step1\main.py:20  >>      main()  >>
        pyproj_dir = C:/Users/Administrator
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step1\init_key_params.py:68       >>
        init_key_params()       >>      [I5239] is_full_python_required = False;        is_embed_python_required = False;       is_pip_required = False
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step2\prebuild_dist_dirs.py:48    >>
        main()  >>      the suggest source root directory is: C:/Users/Administrator
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step2\dist_tree.py:74     >>      build_dst_dirs()        >>
    [0] self.paths:
        ['C:/Users/Administrator/hello_world']
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step2\dist_tree.py:59     >>      _mkdir()        >>      [D0604] create empty folder;    dir_ = C:/dist/hello_world_0.4.7/src/hello_world
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step3\step3_1\main.py:15  >>      main()
        >>      model paths overview
    [0] _:
        ('C:/Users/Administrator', 'C:/Users/Administrator/hello_world')
    [1] _:
        ('C:/dist/hello_world_0.4.7',
         'C:/dist/hello_world_0.4.7/src',
         'C:/dist/hello_world_0.4.7/src/hello_world')
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step3\step3_1\exclusions.py:36    >>
        _indexing_global_exlusion_list()        >>      attachments exclusions overview
    [0] self.excluded_filenames:
        ('.git', '.gitignore', '.gitkeep')
    [1] self.excluded_dirnames:
        ('__pycache__', '.git', '.idea', '.svn', '.vscode')
    [2] self.excluded_paths:
        set()
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step3\step3_2\compile_pyfiles.py:9
        >>      get_compiler()  >>      [I1028] compiler name;  name = pyportable_crypto
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\compilers\pyportable_encryptor.py:42        >>
        __init__()      >>      [D2858] key = _trial
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\compilers\pyportable_encryptor.py:45        >>
        __init__()      >>      [I3130] note: the PyportableEncryptor is running under trial mode, the `key` attribute is invalid.
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\compilers\pyportable_encryptor.py:113       >>
        _load_encryption_func() >>      [D3149] pyportable_crypto.__version__ = 0.2.1-trial;    pyportable_crypto.__file__ = C:\Program Files/Python39/lib/site-packages/pyportable_installer/compilers/accessory/pyportable_crypto_trial_python39\pyportable_crypto\__init__.py
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\compilers\pyportable_encryptor.py:155       >>
        compile_all()   >>      [1/1] compiling;        hello.py
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step3\step3_3\create_launcher.py:228
        >>      _run()  >>      converting bat to exe ... (it may take several seconds ~ one minute)

 Creating EXE
 Filename: ...\hello_world_0.4.7\Hello World.exe
 Exe-Format: 64 Bit | Console (Visible)
 Adding icon... OK
 Adding resources... OK
 Process finished
 ..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step3\step3_3\create_launcher.py:231
        >>      _run()  >>      convertion bat-to-exe done
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main_flow\step1\main.py:20  >>      main()  >>
        pyproj_dir = C:/Users/Administrator
..\..\Program Files\Python39\lib\site-packages\pyportable_installer\main.py:126 >>      main()  >>      [I2501] See distributed project at:
        "...:0" >> hello_world_0.4.7

**Comment by likianta** [comment]
你好, "DLL load failed ..." 该报错初步认为是 Python 解释器版本与 `~/lib/pyportable_runtime/inject.pyd` 的编译版本不同导致的.

由默认的 hello world 示例产生的打包结果中, 其 `lib/pyportable_runtime/inject.pyd` 文件是 **Python 3.9** 编译的.

使用 Python 3.8 或以下的解释器启动, 就会产生此错误.

该现象可由下面的操作复现:

1. 打开 CMD
2. 切换到打包结果所在的目录
3. 输入 `"C:\Program Files\Python38\python.exe" src\pylauncher.py` (请将示例路径替换为您的实际路径)
    1. 产生 "DLL load failed ..." 报错
4. 输入 `"C:\Program Files\Python39\python.exe" src\pylauncher.py`
    1. 程序正确运行

![snipaste_20210928_234445](https://user-images.githubusercontent.com/27986259/135120793-e8a123bd-40a0-4d6c-968e-a93ce7e6536c.png)

**Comment by likianta** [comment]
最近的更新已修复此错误, 请尝试重新拉取项目. 如果此问题仍然发生, 欢迎再次提问!

**Comment by MeteorShower2004** [comment]
谢谢你的回答。
我把pyproject.json里venv的python_version改成3.9，构建完发现又可以了。。（其他一个字都没动过）
### 修改后的内容：
_"venv": {
            "enable_venv": false,
            ...
            "python_version": "3.9",
            ...
}_
**但是当我又把它改回3.8，删除构建过的文件再构建，发现仍然出现此错误**。然我感到奇怪的是明明没有启用venv，但是venv底下的python_version仍然决定了文件的运行效果
不知道这个问题在新的版本中有没有修复。

**Comment by likianta** [comment]
是的, 新版本中已得到修复! `python_version` 使用 '3.8' | '3.9' 均可以正常编译.

此外:

- `enable_venv` 选项用于指定 "创建一个虚拟环境" (true) 还是 "使用电脑系统已安装的 python" (false). 
- 无论是否开关, `python_version` 都起作用, 它将为虚拟环境或系统 python 指定其 *解释器版本*.

近期的更新着重解决了 `python_version` 指定的版本与 `<dist>/lib/pyportable_runtime/inject.pyd` 编译版本不协调的问题.
