### ISSUE TITLE
只支持python3.8及以上吗？

### ISSUE THREAD

**Issue by ZyMousai** [likianta/pyportable-installer#3]
一直在寻找pyinstall的替代品，pyinstall打包的opencv实在忍受不了。找到此项目，可惜我项目是2.7

**Comment by likianta** [comment]
运行 pyportable-installer 需要 3.8 及以上的解释器, 要打包的项目所依赖的版本 *理论上* 没有该限制. 即在配置文件中指定项目版本后 (2.7 ~ 3.10), 以 Python 3.8+ 运行 pyportable-installer 可尝试对其打包.

但目前我在最近的测试中未能实现对 2.7 的打包, 还有许多兼容性工作要做.

该工作的优先级较低, 很抱歉短时期内无法满足你的需求.
