### ISSUE TITLE
LKlogger object has no attribute logt

### ISSUE THREAD

**Issue by fxyz999** [likianta/pyportable-installer#4]
Python 3.10.3
Poetry 1.1.13

![image](https://user-images.githubusercontent.com/538984/159960589-92445d64-0cf7-416e-b8a5-4946e324a2e1.jpeg)

**Comment by likianta** [comment]
The AttributeError points out `embed_python_manager` (it's one of pyportable_installer's dependencies) is using an old version of `lk_logger` library.

Currently (Mar 22th) the `lk_logger` has significantly upgraded from 4.0 to 5.0. But I forgot to check version spec conflicts among all its dependencies:

Now I have released a newer version to resolve this, please pip install:

```shell
pip install pyportable-installer>=4.3.3
```

If it worked, `embed_python_manager` will do like this:

![20220326175755](https://user-images.githubusercontent.com/27986259/160235109-b438852f-9f93-4fb8-bdf0-b016608c3a02.png)

![20220326175859](https://user-images.githubusercontent.com/27986259/160235115-f63d69eb-b69d-4642-8db5-911381196767.png)
