### ISSUE TITLE
 Error: No such option: --format

### ISSUE THREAD

**Issue by I-love-study** [likianta/pyportable-installer#5]
我尝试根据 <https://github.com/likianta/pyportable-installer/blob/master/docs/pyproject-manual.md> 里介绍的方式，创建一个 pyproject.toml 来使用，但是当我尝试使用 `python -m pyportable_installer init --format=toml` 命令创建的时候，却直接报错：
``` bash
Error: No such option: --format
```
根据 `python -m pyportable_installer init -h` 查看帮助，好像现在 Init 已经没有了 `--format` 之类的参数了
那该怎么搞呢

**Comment by likianta** [comment]
抱歉, `--format` 参数目前是不受支持的. 

在编写文档时, 我预留了这个命令但并未实现. 此处有个 *TODO* 标记可能不太明显:

![XFDii7Xfww](https://user-images.githubusercontent.com/27986259/163906374-3b12a3ba-7330-45bf-ad00-2d14a1550686.png)

真实的命令请以 `python -m pyportable_installer init -h` 为准. 目前而言 `init` 仅接受一个可选的目录路径参数, 并创建 json 格式的配置文件:

![kIoJYPS6dS](https://user-images.githubusercontent.com/27986259/163906393-4d243bcb-b4c2-4a28-bb28-2297851ea3c7.png)

我会在近期隐藏文档中的相关说明. 并在下个版本支持后重新展示.
