### ISSUE TITLE
ImportError: cannot import name 'std_print' from 'lk_logger.general' 

### ISSUE THREAD

**Issue by zycool** [likianta/pyportable-installer#7]
你好，还在维护吗？
 F:\WorkPlace\CTPWorkPlace\TqTest2022\env\lib\site-packages\embed_python_man │
│ ager\downloader.py:97 in download                                           │
│                                                                             │
│    94                                                                       │
│    95                                                                       │
│    96 def download(link, file, exist_ok=True):                              │
│ >  97 │   from lk_logger.general import std_print                           │
│    98 │                                                                     │
│    99 │   if exists(file):                                                  │
│   100 │   │   if exist_ok: 

ImportError: cannot import name 'std_print' from 'lk_logger.general' 
(F:\WorkPlace\CTPWorkPlace\TqTest2022\env\lib\site-packages\lk_logger\general.p
y)

**Comment by likianta** [comment]
这个报错应该是指它的依赖库版本过时了, 我在明天尝试修复一下.

**Comment by KaHuier** [comment]
注释掉该行导入 并把使用到std_print的 我看了使用到该函数的代码 我想这只是一个日志输出 我替换成print 终于可以用了

**Comment by likianta** [comment]
在最新的版本 (4.4.2) 中, 该问题已经被修复. 很抱歉拖了这么久, 该项目这几个月的更新频率较低, 但仍在准备一些较大的更新. 我目前在周边工作上进行努力.
